Remove definition of PACKAGE macro (#68).
It collides with LLVM:
/usr/local/include/clang/StaticAnalyzer/Core/AnalyzerOptions.h:437:9: error: 'PACKAGE' macro redefined [-Werror,-Wmacro-redefined]