clangbinarysearch: Fix TypeError due to byte-str mixup
Fix the regression introduced in #265:

  File "\cvise/utils/testing.py", line 151, in run
    (result, self.state) = self.transform(
                           ~~~~~~~~~~~~~~^
        str(self.test_case_path), self.state, ProcessEventNotifier(self.pid_queue)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "\cvise/passes/clangbinarysearch.py", line 117, in transform
    self.parse_stderr(state, stderr)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "\cvise/passes/clangbinarysearch.py", line 90, in parse_stderr
    for line in stderr.split('\n'):
                ~~~~~~~~~~~~^^^^^^
  TypeError: a bytes-like object is required, not 'str'

This pass has only minor importance currently, being gradually superseded by
ClangHints, still as long as it's still present we should fix the error.