clang_delta: llvm-12: prefer getBufferOrNone to getBuffer
../clang_delta/Transformation.cpp:111:51: error: no member named
'getBuffer' in 'clang::SourceManager'
const llvm::MemoryBuffer *MainBuf = SrcManager->getBuffer(MainFileID);
                                    ~~~~~~~~~~  ^

This method was removed in 51d1d585e5838ea0f02f1271f7543c4e43639969.