Fix colordiff exception (#313)
Fix a bug causing the following exception when --print-diff is used,
colordiff is installed and the output is a terminal tty:

  TypeError: memoryview: a bytes-like object is required, not 'str'

Also make the code robust to colordiff failures.